version: "3.8"

services:
  web-test:
    image: nginx:alpine
    networks:
      - public
    deploy:
      replicas: 4
      labels:
        - traefik.enable=true
        - traefik.docker.network=public

        - traefik.http.routers.webtest.rule=Host(`tadeubarbosa.work`)
        - traefik.http.routers.webtest.entrypoints=web
        - traefik.http.routers.webtest.service=webtest

        - traefik.http.services.webtest.loadbalancer.server.port=80

networks:
  public:
    external: true
