version: "3.8"

services:
  app:
    image: infra-app:latest
    networks:
      - public
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=public

        - traefik.http.routers.app.rule=Host(`tadeubarbosa.work`)
        - traefik.http.routers.app.entrypoints=web
        - traefik.http.routers.app.service=app

        - traefik.http.services.app.loadbalancer.server.port=80

networks:
  public:
    external: true
