version: "3.8"

services:
  api:
    image: ghcr.io/tadeubdev/infra-swarm-api:1.2
    networks:
      - public
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=public

        - traefik.http.routers.api.rule=Host(`api.tadeubarbosa.work`)
        - traefik.http.routers.api.entrypoints=web
        - traefik.http.routers.api.service=api

        - traefik.http.services.api.loadbalancer.server.port=3000

networks:
  public:
    external: true